In [13]:
%reload_ext autoreload
%autoreload 2
import os
import glob
import scipy.io.wavfile as wv
import matplotlib.pyplot as plt
import numpy as np
from util import util
import scipy.signal as sig

import numpy
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

In [2]:
nrFiles = 2
Y_train = np.array((np.ones(nrFiles),np.zeros(nrFiles), np.zeros(nrFiles))).T

nrFiles = 4
Y_train_nw = np.array((np.zeros(nrFiles),np.ones(nrFiles), np.zeros(nrFiles))).T
Y_train = np.concatenate((Y_train, Y_train_nw),axis=0)

nrFiles = 3
Y_train_nw = np.array((np.zeros(nrFiles),np.zeros(nrFiles), np.ones(nrFiles))).T
Y_train = np.concatenate((Y_train, Y_train_nw),axis=0)
print(np.shape(Y_train))
print(Y_train)

(9, 3)
[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]]


In [3]:
import pandas

# load dataset
dataframe = pandas.read_csv("dummy/iris.csv", header=None)
dataset = dataframe.values
X = dataset[1:,0:4].astype(float)
Y = dataset[1:,4]


In [4]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)


In [5]:
encoded_Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [6]:
encoder

LabelEncoder()

In [7]:
Y

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [8]:
dummy_y

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.

In [9]:
dataframe

0            1             2            3          4
0    sepal_length  sepal_width  petal_length  petal_width    species
1             5.1          3.5           1.4          0.2     setosa
2             4.9            3           1.4          0.2     setosa
3             4.7          3.2           1.3          0.2     setosa
4             4.6          3.1           1.5          0.2     setosa
5               5          3.6           1.4          0.2     setosa
6             5.4          3.9           1.7          0.4     setosa
7             4.6          3.4           1.4          0.3     setosa
8               5          3.4           1.5          0.2     setosa
9             4.4          2.9           1.4          0.2     setosa
10            4.9          3.1           1.5          0.1     setosa
11            5.4          3.7           1.5          0.2     setosa
12            4.8          3.4           1.6          0.2     setosa
13            4.8            3           1.4          0.1     setosa
14            4.3            3           1.1          0.1     setosa
15            5.8            4           1.2          0.2     setosa
16            5.7          4.4           1.5          0.4     setosa
17            5.4          3.9           1.3          0.4     setosa
18            5.1          3.5           1.4          0.3     setosa
19            5.7          3.8           1.7          0.3     setosa
20            5.1          3.8           1.5          0.3     setosa
21            5.4          3.4           1.7          0.2     setosa
22            5.1          3.7           1.5          0.4     setosa
23            4.6          3.6             1          0.2     setosa
24            5.1          3.3           1.7          0.5     setosa
25            4.8          3.4           1.9          0.2     setosa
26              5            3           1.6          0.2     setosa
27              5          3.4           1.6          0.4     setosa
28            5.2          3.5           1.5          0.2     setosa
29            5.2          3.4           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
121           6.9          3.2           5.7          2.3  virginica
122           5.6          2.8           4.9            2  virginica
123           7.7          2.8           6.7            2  virginica
124           6.3          2.7           4.9          1.8  virginica
125           6.7          3.3           5.7          2.1  virginica
126           7.2          3.2             6          1.8  virginica
127           6.2          2.8           4.8          1.8  virginica
128           6.1            3           4.9          1.8  virginica
129           6.4          2.8           5.6          2.1  virginica
130           7.2            3           5.8          1.6  virginica
131           7.4          2.8           6.1          1.9  virginica
132           7.9          3.8           6.4            2  virginica
133           6.4          2.8           5.6          2.2  virginica
134           6.3          2.8           5.1          1.5  virginica
135           6.1          2.6           5.6          1.4  virginica
136           7.7            3           6.1          2.3  virginica
137           6.3          3.4           5.6          2.4  virginica
138           6.4          3.1           5.5          1.8  virginica
139             6            3           4.8          1.8  virginica
140           6.9          3.1           5.4          2.1  virginica
141           6.7          3.1           5.6          2.4  virginica
142           6.9          3.1           5.1          2.3  virginica
143           5.8          2.7           5.1          1.9  virginica
144           6.8          3.2           5.9          2.3  virginica
145           6.7          3.3           5.7          2.5  virginica
146           6.7            3           5.2          2.3  virginica
147           

In [10]:
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [11]:
# define baseline model
def baseline_model():
	# create model
	model = Sequential()
	model.add(Dense(8, input_dim=4, activation='relu'))
	model.add(Dense(3, activation='softmax'))
	# Compile model
	model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

In [19]:
estimator = KerasClassifier(build_fn=baseline_model, epochs=200, batch_size=5, verbose=1)

In [20]:
# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)
kfold = KFold(n_splits=10, shuffle=True, random_state=seed)

In [21]:
results = cross_val_score(estimator, X, dummy_y, cv=kfold)
print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Epoch 1/200
135/135 [==============================] - 0s 3ms/step - loss: 1.2226 - acc: 0.3333
Epoch 2/200
135/135 [==============================] - 0s 829us/step - loss: 1.1148 - acc: 0.4741
Epoch 3/200
135/135 [==============================] - 0s 658us/step - loss: 1.0349 - acc: 0.6815
Epoch 4/200
135/135 [==============================] - 0s 607us/step - loss: 0.9960 - acc: 0.6815
Epoch 5/200
135/135 [==============================] - 0s 614us/step - loss: 0.9656 - acc: 0.6815
Epoch 6/200
135/135 [==============================] - 0s 614us/step - loss: 0.9354 - acc: 0.6815
Epoch 7/200
135/135 [==============================] - 0s 799us/step - loss: 0.9070 - acc: 0.6815
Epoch 8/200
135/135 [==============================] - 0s 636us/step - loss: 0.8783 - acc: 0.6815
Epoch 9/200
135/135 [==============================] - 0s 585us/step - loss: 0.8505 - acc: 0.6815
Epoch 10/200
135/135 [==============================] - 0s 570us/step - loss: 0.8244 - acc: 0.6815
Epoch 11/200
135/135 

135/135 [==============================] - 0s 688us/step - loss: 0.2463 - acc: 0.9704
Epoch 84/200
135/135 [==============================] - 0s 681us/step - loss: 0.2425 - acc: 0.9630
Epoch 85/200
135/135 [==============================] - 0s 570us/step - loss: 0.2391 - acc: 0.9704
Epoch 86/200
135/135 [==============================] - 0s 562us/step - loss: 0.2364 - acc: 0.9704
Epoch 87/200
135/135 [==============================] - 0s 540us/step - loss: 0.2338 - acc: 0.9704
Epoch 88/200
135/135 [==============================] - 0s 555us/step - loss: 0.2324 - acc: 0.9704
Epoch 89/200
135/135 [==============================] - 0s 555us/step - loss: 0.2291 - acc: 0.9704
Epoch 90/200
135/135 [==============================] - 0s 548us/step - loss: 0.2261 - acc: 0.9704
Epoch 91/200
135/135 [==============================] - 0s 555us/step - loss: 0.2252 - acc: 0.9704
Epoch 92/200
135/135 [==============================] - 0s 562us/step - loss: 0.2208 - acc: 0.9704
Epoch 93/200
135/135 [=

135/135 [==============================] - 0s 548us/step - loss: 0.1178 - acc: 0.9778
Epoch 166/200
135/135 [==============================] - 0s 562us/step - loss: 0.1181 - acc: 0.9704
Epoch 167/200
135/135 [==============================] - 0s 577us/step - loss: 0.1161 - acc: 0.9778
Epoch 168/200
135/135 [==============================] - 0s 548us/step - loss: 0.1168 - acc: 0.9778
Epoch 169/200
135/135 [==============================] - 0s 555us/step - loss: 0.1145 - acc: 0.9778
Epoch 170/200
135/135 [==============================] - 0s 548us/step - loss: 0.1156 - acc: 0.9778
Epoch 171/200
135/135 [==============================] - 0s 533us/step - loss: 0.1142 - acc: 0.9778
Epoch 172/200
135/135 [==============================] - 0s 540us/step - loss: 0.1148 - acc: 0.9704
Epoch 173/200
135/135 [==============================] - 0s 570us/step - loss: 0.1175 - acc: 0.9704
Epoch 174/200
135/135 [==============================] - 0s 562us/step - loss: 0.1130 - acc: 0.9778
Epoch 175/200


135/135 [==============================] - 0s 577us/step - loss: 0.2182 - acc: 0.9778
Epoch 48/200
135/135 [==============================] - 0s 555us/step - loss: 0.2154 - acc: 0.9778
Epoch 49/200
135/135 [==============================] - 0s 562us/step - loss: 0.2063 - acc: 0.9778
Epoch 50/200
135/135 [==============================] - 0s 555us/step - loss: 0.2026 - acc: 0.9778
Epoch 51/200
135/135 [==============================] - 0s 644us/step - loss: 0.1992 - acc: 0.9778
Epoch 52/200
135/135 [==============================] - 0s 622us/step - loss: 0.1965 - acc: 0.9778
Epoch 53/200
135/135 [==============================] - 0s 614us/step - loss: 0.1962 - acc: 0.9778
Epoch 54/200
135/135 [==============================] - 0s 651us/step - loss: 0.1922 - acc: 0.9704
Epoch 55/200
135/135 [==============================] - 0s 725us/step - loss: 0.1865 - acc: 0.9778
Epoch 56/200
135/135 [==============================] - 0s 548us/step - loss: 0.1856 - acc: 0.9778
Epoch 57/200
135/135 [=

135/135 [==============================] - 0s 548us/step - loss: 0.0906 - acc: 0.9704
Epoch 130/200
135/135 [==============================] - 0s 562us/step - loss: 0.0889 - acc: 0.9778
Epoch 131/200
135/135 [==============================] - 0s 555us/step - loss: 0.0876 - acc: 0.9778
Epoch 132/200
135/135 [==============================] - 0s 614us/step - loss: 0.0896 - acc: 0.9704
Epoch 133/200
135/135 [==============================] - 0s 644us/step - loss: 0.0887 - acc: 0.9778
Epoch 134/200
135/135 [==============================] - 0s 570us/step - loss: 0.0894 - acc: 0.9704
Epoch 135/200
135/135 [==============================] - 0s 562us/step - loss: 0.0879 - acc: 0.9778
Epoch 136/200
135/135 [==============================] - 0s 570us/step - loss: 0.0859 - acc: 0.9778
Epoch 137/200
135/135 [==============================] - 0s 548us/step - loss: 0.0843 - acc: 0.9778
Epoch 138/200
135/135 [==============================] - 0s 533us/step - loss: 0.0838 - acc: 0.9778
Epoch 139/200


135/135 [==============================] - 0s 548us/step - loss: 1.2313 - acc: 0.3407
Epoch 11/200
135/135 [==============================] - 0s 555us/step - loss: 1.1792 - acc: 0.3407
Epoch 12/200
135/135 [==============================] - 0s 577us/step - loss: 1.1421 - acc: 0.3407
Epoch 13/200
135/135 [==============================] - 0s 577us/step - loss: 1.1140 - acc: 0.3407
Epoch 14/200
135/135 [==============================] - 0s 555us/step - loss: 1.0926 - acc: 0.3407
Epoch 15/200
135/135 [==============================] - 0s 562us/step - loss: 1.0766 - acc: 0.3407
Epoch 16/200
135/135 [==============================] - 0s 562us/step - loss: 1.0651 - acc: 0.3852
Epoch 17/200
135/135 [==============================] - 0s 585us/step - loss: 1.0526 - acc: 0.4296
Epoch 18/200
135/135 [==============================] - 0s 548us/step - loss: 1.0420 - acc: 0.5259
Epoch 19/200
135/135 [==============================] - 0s 548us/step - loss: 1.0308 - acc: 0.6148
Epoch 20/200
135/135 [=

135/135 [==============================] - 0s 562us/step - loss: 0.3281 - acc: 0.9556
Epoch 93/200
135/135 [==============================] - 0s 562us/step - loss: 0.3234 - acc: 0.9556
Epoch 94/200
135/135 [==============================] - 0s 548us/step - loss: 0.3195 - acc: 0.9407
Epoch 95/200
135/135 [==============================] - 0s 577us/step - loss: 0.3170 - acc: 0.9407
Epoch 96/200
135/135 [==============================] - 0s 548us/step - loss: 0.3128 - acc: 0.9481
Epoch 97/200
135/135 [==============================] - 0s 555us/step - loss: 0.3076 - acc: 0.9481
Epoch 98/200
135/135 [==============================] - 0s 577us/step - loss: 0.3041 - acc: 0.9481
Epoch 99/200
135/135 [==============================] - 0s 548us/step - loss: 0.2992 - acc: 0.9556
Epoch 100/200
135/135 [==============================] - 0s 555us/step - loss: 0.2959 - acc: 0.9556
Epoch 101/200
135/135 [==============================] - 0s 562us/step - loss: 0.2919 - acc: 0.9556
Epoch 102/200
135/135

135/135 [==============================] - 0s 548us/step - loss: 0.1471 - acc: 0.9630
Epoch 175/200
135/135 [==============================] - 0s 599us/step - loss: 0.1453 - acc: 0.9630
Epoch 176/200
135/135 [==============================] - 0s 733us/step - loss: 0.1440 - acc: 0.9556
Epoch 177/200
135/135 [==============================] - 0s 607us/step - loss: 0.1440 - acc: 0.9556
Epoch 178/200
135/135 [==============================] - 0s 548us/step - loss: 0.1427 - acc: 0.9556
Epoch 179/200
135/135 [==============================] - 0s 540us/step - loss: 0.1428 - acc: 0.9556
Epoch 180/200
135/135 [==============================] - 0s 762us/step - loss: 0.1399 - acc: 0.9630
Epoch 181/200
135/135 [==============================] - 0s 644us/step - loss: 0.1408 - acc: 0.9556
Epoch 182/200
135/135 [==============================] - 0s 562us/step - loss: 0.1386 - acc: 0.9556
Epoch 183/200
135/135 [==============================] - 0s 562us/step - loss: 0.1377 - acc: 0.9556
Epoch 184/200


135/135 [==============================] - 0s 540us/step - loss: 0.3233 - acc: 0.9704
Epoch 57/200
135/135 [==============================] - 0s 555us/step - loss: 0.3192 - acc: 0.9704
Epoch 58/200
135/135 [==============================] - 0s 577us/step - loss: 0.3120 - acc: 0.9704
Epoch 59/200
135/135 [==============================] - 0s 555us/step - loss: 0.3099 - acc: 0.9704
Epoch 60/200
135/135 [==============================] - 0s 548us/step - loss: 0.3060 - acc: 0.9704
Epoch 61/200
135/135 [==============================] - 0s 540us/step - loss: 0.2997 - acc: 0.9704
Epoch 62/200
135/135 [==============================] - 0s 555us/step - loss: 0.2953 - acc: 0.9704
Epoch 63/200
135/135 [==============================] - 0s 570us/step - loss: 0.2893 - acc: 0.9704
Epoch 64/200
135/135 [==============================] - 0s 562us/step - loss: 0.2856 - acc: 0.9630
Epoch 65/200
135/135 [==============================] - 0s 548us/step - loss: 0.2831 - acc: 0.9704
Epoch 66/200
135/135 [=

135/135 [==============================] - 0s 570us/step - loss: 0.1190 - acc: 0.9778
Epoch 139/200
135/135 [==============================] - 0s 570us/step - loss: 0.1204 - acc: 0.9778
Epoch 140/200
135/135 [==============================] - 0s 562us/step - loss: 0.1179 - acc: 0.9704
Epoch 141/200
135/135 [==============================] - 0s 555us/step - loss: 0.1163 - acc: 0.9704
Epoch 142/200
135/135 [==============================] - 0s 548us/step - loss: 0.1144 - acc: 0.9778
Epoch 143/200
135/135 [==============================] - 0s 555us/step - loss: 0.1153 - acc: 0.9704
Epoch 144/200
135/135 [==============================] - 0s 548us/step - loss: 0.1136 - acc: 0.9778
Epoch 145/200
135/135 [==============================] - 0s 540us/step - loss: 0.1149 - acc: 0.9630
Epoch 146/200
135/135 [==============================] - 0s 548us/step - loss: 0.1137 - acc: 0.9704
Epoch 147/200
135/135 [==============================] - 0s 555us/step - loss: 0.1106 - acc: 0.9778
Epoch 148/200


135/135 [==============================] - 0s 577us/step - loss: 0.6295 - acc: 0.6000
Epoch 20/200
135/135 [==============================] - 0s 562us/step - loss: 0.6187 - acc: 0.6296
Epoch 21/200
135/135 [==============================] - 0s 622us/step - loss: 0.5900 - acc: 0.7037
Epoch 22/200
135/135 [==============================] - 0s 636us/step - loss: 0.5746 - acc: 0.7407
Epoch 23/200
135/135 [==============================] - 0s 599us/step - loss: 0.5606 - acc: 0.8296
Epoch 24/200
135/135 [==============================] - 0s 533us/step - loss: 0.5454 - acc: 0.8074
Epoch 25/200
135/135 [==============================] - 0s 548us/step - loss: 0.5312 - acc: 0.8667
Epoch 26/200
135/135 [==============================] - 0s 577us/step - loss: 0.5197 - acc: 0.8889
Epoch 27/200
135/135 [==============================] - 0s 548us/step - loss: 0.5075 - acc: 0.9111
Epoch 28/200
135/135 [==============================] - 0s 562us/step - loss: 0.4939 - acc: 0.9556
Epoch 29/200
135/135 [=

135/135 [==============================] - 0s 562us/step - loss: 0.1651 - acc: 0.9778
Epoch 102/200
135/135 [==============================] - 0s 555us/step - loss: 0.1659 - acc: 0.9778
Epoch 103/200
135/135 [==============================] - 0s 555us/step - loss: 0.1620 - acc: 0.9852
Epoch 104/200
135/135 [==============================] - 0s 555us/step - loss: 0.1613 - acc: 0.9778
Epoch 105/200
135/135 [==============================] - 0s 592us/step - loss: 0.1631 - acc: 0.9704
Epoch 106/200
135/135 [==============================] - 0s 577us/step - loss: 0.1586 - acc: 0.9778
Epoch 107/200
135/135 [==============================] - 0s 555us/step - loss: 0.1559 - acc: 0.9778
Epoch 108/200
135/135 [==============================] - 0s 548us/step - loss: 0.1552 - acc: 0.9778
Epoch 109/200
135/135 [==============================] - 0s 548us/step - loss: 0.1532 - acc: 0.9852
Epoch 110/200
135/135 [==============================] - 0s 548us/step - loss: 0.1526 - acc: 0.9852
Epoch 111/200


135/135 [==============================] - 0s 555us/step - loss: 0.1034 - acc: 0.9704
Epoch 184/200
135/135 [==============================] - 0s 555us/step - loss: 0.0971 - acc: 0.9778
Epoch 185/200
135/135 [==============================] - 0s 555us/step - loss: 0.0995 - acc: 0.9778
Epoch 186/200
135/135 [==============================] - 0s 555us/step - loss: 0.0977 - acc: 0.9778
Epoch 187/200
135/135 [==============================] - 0s 555us/step - loss: 0.0961 - acc: 0.9778
Epoch 188/200
135/135 [==============================] - 0s 533us/step - loss: 0.0965 - acc: 0.9778
Epoch 189/200
135/135 [==============================] - 0s 533us/step - loss: 0.0971 - acc: 0.9778
Epoch 190/200
135/135 [==============================] - 0s 540us/step - loss: 0.0992 - acc: 0.9778
Epoch 191/200
135/135 [==============================] - 0s 540us/step - loss: 0.1036 - acc: 0.9630
Epoch 192/200
135/135 [==============================] - 0s 548us/step - loss: 0.0958 - acc: 0.9778
Epoch 193/200


135/135 [==============================] - 0s 555us/step - loss: 0.3074 - acc: 0.9630
Epoch 66/200
135/135 [==============================] - 0s 540us/step - loss: 0.3014 - acc: 0.9556
Epoch 67/200
135/135 [==============================] - 0s 703us/step - loss: 0.2998 - acc: 0.9630
Epoch 68/200
135/135 [==============================] - 0s 673us/step - loss: 0.2916 - acc: 0.9556
Epoch 69/200
135/135 [==============================] - 0s 555us/step - loss: 0.2868 - acc: 0.9630
Epoch 70/200
135/135 [==============================] - 0s 540us/step - loss: 0.2830 - acc: 0.9630
Epoch 71/200
135/135 [==============================] - 0s 555us/step - loss: 0.2776 - acc: 0.9630
Epoch 72/200
135/135 [==============================] - 0s 555us/step - loss: 0.2746 - acc: 0.9556
Epoch 73/200
135/135 [==============================] - 0s 562us/step - loss: 0.2708 - acc: 0.9630
Epoch 74/200
135/135 [==============================] - 0s 555us/step - loss: 0.2677 - acc: 0.9630
Epoch 75/200
135/135 [=

135/135 [==============================] - 0s 644us/step - loss: 0.1190 - acc: 0.9704
Epoch 148/200
135/135 [==============================] - 0s 570us/step - loss: 0.1193 - acc: 0.9704
Epoch 149/200
135/135 [==============================] - 0s 533us/step - loss: 0.1174 - acc: 0.9704
Epoch 150/200
135/135 [==============================] - 0s 562us/step - loss: 0.1177 - acc: 0.9704
Epoch 151/200
135/135 [==============================] - 0s 570us/step - loss: 0.1177 - acc: 0.9704
Epoch 152/200
135/135 [==============================] - 0s 577us/step - loss: 0.1158 - acc: 0.9704
Epoch 153/200
135/135 [==============================] - 0s 540us/step - loss: 0.1169 - acc: 0.9704
Epoch 154/200
135/135 [==============================] - 0s 577us/step - loss: 0.1145 - acc: 0.9704
Epoch 155/200
135/135 [==============================] - 0s 585us/step - loss: 0.1135 - acc: 0.9704
Epoch 156/200
135/135 [==============================] - 0s 562us/step - loss: 0.1128 - acc: 0.9704
Epoch 157/200


135/135 [==============================] - 0s 555us/step - loss: 0.6111 - acc: 0.7630
Epoch 29/200
135/135 [==============================] - 0s 548us/step - loss: 0.5987 - acc: 0.7704
Epoch 30/200
135/135 [==============================] - 0s 577us/step - loss: 0.5869 - acc: 0.8148
Epoch 31/200
135/135 [==============================] - 0s 577us/step - loss: 0.5754 - acc: 0.8000
Epoch 32/200
135/135 [==============================] - 0s 548us/step - loss: 0.5641 - acc: 0.8370
Epoch 33/200
135/135 [==============================] - 0s 540us/step - loss: 0.5555 - acc: 0.7926
Epoch 34/200
135/135 [==============================] - 0s 659us/step - loss: 0.5436 - acc: 0.8519
Epoch 35/200
135/135 [==============================] - 0s 666us/step - loss: 0.5345 - acc: 0.8741
Epoch 36/200
135/135 [==============================] - 0s 585us/step - loss: 0.5233 - acc: 0.8815
Epoch 37/200
135/135 [==============================] - 0s 577us/step - loss: 0.5159 - acc: 0.9037
Epoch 38/200
135/135 [=

135/135 [==============================] - 0s 562us/step - loss: 0.1803 - acc: 0.9778
Epoch 111/200
135/135 [==============================] - 0s 784us/step - loss: 0.1794 - acc: 0.9778
Epoch 112/200
135/135 [==============================] - 0s 636us/step - loss: 0.1756 - acc: 0.9778
Epoch 113/200
135/135 [==============================] - 0s 555us/step - loss: 0.1741 - acc: 0.9778
Epoch 114/200
135/135 [==============================] - 0s 548us/step - loss: 0.1725 - acc: 0.9778
Epoch 115/200
135/135 [==============================] - 0s 555us/step - loss: 0.1711 - acc: 0.9778
Epoch 116/200
135/135 [==============================] - 0s 570us/step - loss: 0.1687 - acc: 0.9778
Epoch 117/200
135/135 [==============================] - 0s 562us/step - loss: 0.1697 - acc: 0.9778
Epoch 118/200
135/135 [==============================] - 0s 548us/step - loss: 0.1689 - acc: 0.9704
Epoch 119/200
135/135 [==============================] - 0s 562us/step - loss: 0.1644 - acc: 0.9778
Epoch 120/200


135/135 [==============================] - 0s 570us/step - loss: 0.0969 - acc: 0.9778
Epoch 193/200
135/135 [==============================] - 0s 555us/step - loss: 0.0969 - acc: 0.9852
Epoch 194/200
135/135 [==============================] - 0s 555us/step - loss: 0.0974 - acc: 0.9778
Epoch 195/200
135/135 [==============================] - 0s 562us/step - loss: 0.0957 - acc: 0.9704
Epoch 196/200
135/135 [==============================] - 0s 585us/step - loss: 0.0952 - acc: 0.9778
Epoch 197/200
135/135 [==============================] - 0s 555us/step - loss: 0.0942 - acc: 0.9704
Epoch 198/200
135/135 [==============================] - 0s 548us/step - loss: 0.0954 - acc: 0.9778
Epoch 199/200
135/135 [==============================] - 0s 636us/step - loss: 0.0946 - acc: 0.9778
Epoch 200/200
15/15 [==============================] - 0s 7ms/step
Epoch 1/200
135/135 [==============================] - 1s 4ms/step - loss: 1.9022 - acc: 0.3333
Epoch 2/200
135/135 [==============================

135/135 [==============================] - 0s 577us/step - loss: 0.2796 - acc: 0.9630
Epoch 75/200
135/135 [==============================] - 0s 555us/step - loss: 0.2757 - acc: 0.9704
Epoch 76/200
135/135 [==============================] - 0s 555us/step - loss: 0.2739 - acc: 0.9704
Epoch 77/200
135/135 [==============================] - 0s 540us/step - loss: 0.2691 - acc: 0.9630
Epoch 78/200
135/135 [==============================] - 0s 703us/step - loss: 0.2685 - acc: 0.9704
Epoch 79/200
135/135 [==============================] - 0s 733us/step - loss: 0.2609 - acc: 0.9704
Epoch 80/200
135/135 [==============================] - 0s 548us/step - loss: 0.2581 - acc: 0.9630
Epoch 81/200
135/135 [==============================] - 0s 555us/step - loss: 0.2559 - acc: 0.9556
Epoch 82/200
135/135 [==============================] - 0s 570us/step - loss: 0.2550 - acc: 0.9630
Epoch 83/200
135/135 [==============================] - 0s 555us/step - loss: 0.2493 - acc: 0.9704
Epoch 84/200
135/135 [=

135/135 [==============================] - 0s 562us/step - loss: 0.1240 - acc: 0.9630
Epoch 157/200
135/135 [==============================] - 0s 762us/step - loss: 0.1214 - acc: 0.9778
Epoch 158/200
135/135 [==============================] - 0s 659us/step - loss: 0.1184 - acc: 0.9704
Epoch 159/200
135/135 [==============================] - 0s 562us/step - loss: 0.1185 - acc: 0.9778
Epoch 160/200
135/135 [==============================] - 0s 555us/step - loss: 0.1175 - acc: 0.9704
Epoch 161/200
135/135 [==============================] - 0s 562us/step - loss: 0.1165 - acc: 0.9778
Epoch 162/200
135/135 [==============================] - 0s 562us/step - loss: 0.1157 - acc: 0.9704
Epoch 163/200
135/135 [==============================] - 0s 570us/step - loss: 0.1155 - acc: 0.9852
Epoch 164/200
135/135 [==============================] - 0s 570us/step - loss: 0.1156 - acc: 0.9778
Epoch 165/200
135/135 [==============================] - 0s 570us/step - loss: 0.1140 - acc: 0.9778
Epoch 166/200


135/135 [==============================] - 0s 548us/step - loss: 0.3426 - acc: 0.9556
Epoch 39/200
135/135 [==============================] - 0s 548us/step - loss: 0.3353 - acc: 0.9481
Epoch 40/200
135/135 [==============================] - 0s 570us/step - loss: 0.3280 - acc: 0.9704
Epoch 41/200
135/135 [==============================] - 0s 592us/step - loss: 0.3223 - acc: 0.9481
Epoch 42/200
135/135 [==============================] - 0s 614us/step - loss: 0.3170 - acc: 0.9556
Epoch 43/200
135/135 [==============================] - 0s 651us/step - loss: 0.3089 - acc: 0.9481
Epoch 44/200
135/135 [==============================] - 0s 585us/step - loss: 0.3026 - acc: 0.9778
Epoch 45/200
135/135 [==============================] - 0s 577us/step - loss: 0.2989 - acc: 0.9481
Epoch 46/200
135/135 [==============================] - 0s 555us/step - loss: 0.2923 - acc: 0.9704
Epoch 47/200
135/135 [==============================] - 0s 592us/step - loss: 0.2841 - acc: 0.9778
Epoch 48/200
135/135 [=

135/135 [==============================] - 0s 540us/step - loss: 0.1091 - acc: 0.9778
Epoch 121/200
135/135 [==============================] - 0s 562us/step - loss: 0.1108 - acc: 0.9704
Epoch 122/200
135/135 [==============================] - 0s 555us/step - loss: 0.1101 - acc: 0.9778
Epoch 123/200
135/135 [==============================] - 0s 555us/step - loss: 0.1100 - acc: 0.9778
Epoch 124/200
135/135 [==============================] - 0s 548us/step - loss: 0.1064 - acc: 0.9778
Epoch 125/200
135/135 [==============================] - 0s 622us/step - loss: 0.1068 - acc: 0.9778
Epoch 126/200
135/135 [==============================] - 0s 696us/step - loss: 0.1061 - acc: 0.9778
Epoch 127/200
135/135 [==============================] - 0s 555us/step - loss: 0.1076 - acc: 0.9704
Epoch 128/200
135/135 [==============================] - 0s 540us/step - loss: 0.1050 - acc: 0.9778
Epoch 129/200
135/135 [==============================] - 0s 555us/step - loss: 0.1046 - acc: 0.9778
Epoch 130/200


135/135 [==============================] - 1s 4ms/step - loss: 4.5425 - acc: 0.3333
Epoch 2/200
135/135 [==============================] - 0s 629us/step - loss: 3.6409 - acc: 0.2000
Epoch 3/200
135/135 [==============================] - 0s 585us/step - loss: 2.9267 - acc: 0.0222
Epoch 4/200
135/135 [==============================] - 0s 599us/step - loss: 2.2712 - acc: 0.0444
Epoch 5/200
135/135 [==============================] - 0s 592us/step - loss: 1.8075 - acc: 0.0815
Epoch 6/200
135/135 [==============================] - 0s 577us/step - loss: 1.5180 - acc: 0.0667
Epoch 7/200
135/135 [==============================] - 0s 577us/step - loss: 1.4167 - acc: 0.2000
Epoch 8/200
135/135 [==============================] - 0s 570us/step - loss: 1.3571 - acc: 0.0741
Epoch 9/200
135/135 [==============================] - 0s 577us/step - loss: 1.2777 - acc: 0.1185
Epoch 10/200
135/135 [==============================] - 0s 585us/step - loss: 1.1809 - acc: 0.2593
Epoch 11/200
135/135 [===========

Epoch 84/200
135/135 [==============================] - 0s 548us/step - loss: 0.1914 - acc: 0.9852
Epoch 85/200
135/135 [==============================] - 0s 555us/step - loss: 0.1882 - acc: 0.9926
Epoch 86/200
135/135 [==============================] - 0s 555us/step - loss: 0.1835 - acc: 0.9926
Epoch 87/200
135/135 [==============================] - 0s 577us/step - loss: 0.1806 - acc: 0.9926
Epoch 88/200
135/135 [==============================] - 0s 548us/step - loss: 0.1792 - acc: 0.9926
Epoch 89/200
135/135 [==============================] - 0s 548us/step - loss: 0.1757 - acc: 0.9926
Epoch 90/200
135/135 [==============================] - 0s 570us/step - loss: 0.1737 - acc: 0.9852
Epoch 91/200
135/135 [==============================] - 0s 747us/step - loss: 0.1707 - acc: 0.9852
Epoch 92/200
135/135 [==============================] - 0s 644us/step - loss: 0.1695 - acc: 0.9926
Epoch 93/200
135/135 [==============================] - 0s 577us/step - loss: 0.1655 - acc: 0.9926
Epoch 94/2

135/135 [==============================] - 0s 555us/step - loss: 0.0856 - acc: 0.9926
Epoch 167/200
135/135 [==============================] - 0s 659us/step - loss: 0.0831 - acc: 0.9926
Epoch 168/200
135/135 [==============================] - 0s 673us/step - loss: 0.0816 - acc: 0.9852
Epoch 169/200
135/135 [==============================] - 0s 548us/step - loss: 0.0806 - acc: 0.9926
Epoch 170/200
135/135 [==============================] - 0s 548us/step - loss: 0.0805 - acc: 0.9852
Epoch 171/200
135/135 [==============================] - 0s 555us/step - loss: 0.0807 - acc: 0.9926
Epoch 172/200
135/135 [==============================] - 0s 555us/step - loss: 0.0821 - acc: 0.9852
Epoch 173/200
135/135 [==============================] - 0s 562us/step - loss: 0.0794 - acc: 0.9852
Epoch 174/200
135/135 [==============================] - 0s 548us/step - loss: 0.0799 - acc: 0.9778
Epoch 175/200
135/135 [==============================] - 0s 555us/step - loss: 0.0769 - acc: 0.9926
Epoch 176/200


In [22]:
results.info()

AttributeError: 'numpy.ndarray' object has no attribute 'info'

In [23]:
results

array([ 1.        ,  0.93333334,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  0.93333334,  1.        ,  0.86666667])

In [24]:
estimator